// generated by vld -type=Wine; DO NOT EDIT

package example

import "github.com/mkasner/vld"

// Validates Wine
func (t *Wine) Validate(ctx vld.Context) vld.Context {
	validator := vld.New().
		Add(vld.Required(t.Kind, "Wine.Kind")).
		Add(vld.MaxLength(10, t.Kind, "Wine.Kind")).
		Add(vld.Required(t.Year, "Wine.Year")).
		Add(vld.MaxInt(3000, t.Year, "Wine.Year")).
		Add(vld.MinInt(1900, t.Year, "Wine.Year"))

	ctx.Err = validator.Validate()

	ctx = t.ValidateOverride(ctx)
	return ctx
}

// Validate override of Wine
// You can implement this in some other file
func (t *Wine) ValidateOverride(ctx vld.Context) vld.Context {
	return ctx
}
